#include "farversion.hpp"

#define PLUGIN_BUILD 9
#define PLUGIN_DESC L"GitAutoComplete Plugin for Far Manager"
#define PLUGIN_NAME L"GitAutoComp"
#define PLUGIN_FILENAME L"GitAutoComp.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
